"""add review and relationships

Revision ID: 01387b4a8eb7
Revises: 82ef11c76e56
Create Date: 2025-06-06 15:13:33.277572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01387b4a8eb7'
down_revision = '82ef11c76e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'email')
    # ### end Alembic commands ###
